from pathlib import Path
from typing import Optional

from .filesystems import FileSystem
from .output import Output
from .execute import Execute


def run_whoami(domain: str, fs: FileSystem, executor: Execute, record_file: str = "record.md") -> None:
    """Execution set 1 scaffold: create recon folder and whoami.md with title.

    This prepares the workspace to later run:
      - host <domain>
      - whois <ip>
      - whois <domain>
    """
    # Folders/files
    fs.createFolder("recon")
    whoami_path = fs.createFile("whoami.md", location="recon")

    # File content
    out = Output()
    out.addTitle("WhoAmI")
    out.newLine()
    out.write_to_file(whoami_path)

    # Record file gets a heading once so it exists already (created by CLI)
    # Future steps will append commands and outputs to both files.


def run_subdomains(domain: str, fs: FileSystem, executor: Execute, record_file: str = "record.md") -> None:
    """Execution set 2 scaffold: create recon/subdomains and base files.

    This prepares the workspace to later run:
      - subfinder
      - curl crt.sh + jq
      - combine/sort/grep steps
    """
    fs.createFolder("recon")
    fs.createFolder("subdomains", location="recon")
    subdomains_path = fs.createFile("subdomains.md", location="recon/subdomains")

    out = Output()
    out.addTitle("Subdomains")
    out.newLine()
    out.write_to_file(subdomains_path)

    # Placeholder: the text file for all subdomains will be generated by later steps

